// -----------------------------------------------------
// This file is generated by a script. DO NOT CHANGE IT!
// -----------------------------------------------------
import Nullstack from "nullstack";
export default ({width, height, length, title, rotation, animation, speed, class: klass, color = "currentColor"}) => {
  const transform = rotation ? `rotate(${rotation})` : false;
  const duration = {slow: "1.5s", fast: "0.5s"}[speed] || "1.0s";
  return (
    <svg width={width} height={height} transform={transform} class={klass} viewBox="0 0 512 512">
      {title && <title>{title}</title>}
      {animation === "spin" && <animateTransform attributeType="xml" attributeName="transform" type="rotate" from="360 0 0" to="0 0 0" dur={duration} additive="sum" repeatCount="indefinite" />}
      <path d="M386.17,390.4539c0-59.9706-58.3872-108.5863-130.4115-108.5863S125.3465,330.4833,125.3465,390.4539Z" transform="translate(0 0)" fill={color}/>
      <ellipse cx="255.7581" cy="193.937" rx="72.4194" ry="72.3908" fill={color}/>
      <ellipse cx="99.2714" cy="238.9143" rx="54.7959" ry="54.7742" fill={color}/>
      <ellipse cx="412.7286" cy="238.9143" rx="54.7959" ry="54.7742" fill={color}/>
      <path d="M140.6316,315.2949a115.8907,115.8907,0,0,0-41.36-7.4986C44.4453,307.7963,0,344.8033,0,390.4539H104.3382C104.3382,361.2845,118.1545,334.804,140.6316,315.2949Z" transform="translate(0 0)" fill={color}/>
      <path d="M412.7286,307.7963a115.8326,115.8326,0,0,0-41.6925,7.6277c22.3885,19.4966,36.1418,45.9254,36.1418,75.03H512C512,344.8033,467.5547,307.7963,412.7286,307.7963Z" transform="translate(0 0)" fill={color}/>
    </svg>
  )
}