// -----------------------------------------------------
// This file is generated by a script. DO NOT CHANGE IT!
// -----------------------------------------------------
import Nullstack from "nullstack";
export default ({width, height, length, title, rotation, animation, speed, class: klass, color = "currentColor"}) => {
  const transform = rotation ? `rotate(${rotation})` : false;
  const duration = {slow: "1.5s", fast: "0.5s"}[speed] || "1.0s";
  return (
    <svg width={width} height={height} transform={transform} class={klass} viewBox="0 0 512 512">
      {title && <title>{title}</title>}
      {animation === "spin" && <animateTransform attributeType="xml" attributeName="transform" type="rotate" from="360 0 0" to="0 0 0" dur={duration} additive="sum" repeatCount="indefinite" />}
      <path d="M433.4,0H78.6A78.6,78.6,0,0,0,0,78.6V433.4A78.6,78.6,0,0,0,78.6,512H256V310.231H190.7838V233.5588H256V172.2211s.1569-83.936,80.0574-83.936h88.7784v73.444H373.1829s-29.0547-2.4212-29.0547,31.4759v38.74h80.7076L415.958,310.231h-71.83V512H433.4A78.6,78.6,0,0,0,512,433.4V78.6A78.6,78.6,0,0,0,433.4,0Z" transform="translate(0 0)" fill={color}/>
    </svg>
  )
}