// -----------------------------------------------------
// This file is generated by a script. DO NOT CHANGE IT!
// -----------------------------------------------------
import Nullstack from "nullstack";
export default ({width, height, length, title, rotation, animation, speed, class: klass, color = "currentColor"}) => {
  const transform = rotation ? `rotate(${rotation})` : false;
  const duration = {slow: "1.5s", fast: "0.5s"}[speed] || "1.0s";
  return (
    <svg width={width} height={height} transform={transform} class={klass} viewBox="0 0 512 512">
      {title && <title>{title}</title>}
      {animation === "spin" && <animateTransform attributeType="xml" attributeName="transform" type="rotate" from="360 0 0" to="0 0 0" dur={duration} additive="sum" repeatCount="indefinite" />}
      <path d="M301.2021,210.7979V27.383A17.3829,17.3829,0,0,0,283.8192,10H228.1809a17.3829,17.3829,0,0,0-17.383,17.383V210.7979H27.383A17.3829,17.3829,0,0,0,10,228.1809v55.6383a17.3829,17.3829,0,0,0,17.383,17.3829H210.7979V484.617A17.383,17.383,0,0,0,228.1808,502h55.6383a17.383,17.383,0,0,0,17.383-17.383V301.2021H484.617A17.383,17.383,0,0,0,502,283.8191V228.1808a17.383,17.383,0,0,0-17.383-17.3829Z" transform="translate(0 0)" fill="none" stroke={color} stroke-linecap="round" stroke-linejoin="round" stroke-width={length || 20}/>
    </svg>
  )
}