// -----------------------------------------------------
// This file is generated by a script. DO NOT CHANGE IT!
// -----------------------------------------------------
import Nullstack from "nullstack";
export default ({width, height, length, title, rotation, animation, speed, class: klass, color = "currentColor"}) => {
  const transform = rotation ? `rotate(${rotation})` : false;
  const duration = {slow: "1.5s", fast: "0.5s"}[speed] || "1.0s";
  return (
    <svg width={width} height={height} transform={transform} class={klass} viewBox="0 0 512 512">
      {title && <title>{title}</title>}
      {animation === "spin" && <animateTransform attributeType="xml" attributeName="transform" type="rotate" from="360 0 0" to="0 0 0" dur={duration} additive="sum" repeatCount="indefinite" />}
      <circle cx="256.0001" cy="256.0001" r="99.0169" transform="translate(-51.9686 65.6652) rotate(-13.2826)" fill={color}/>
      <path d="M409.5956,0H102.4044A102.4044,102.4044,0,0,0,0,102.4044V409.5955A102.4045,102.4045,0,0,0,102.4044,512H409.5956A102.4045,102.4045,0,0,0,512,409.5955V102.4044A102.4044,102.4044,0,0,0,409.5956,0ZM256,407.05c-83.2886,0-151.0493-67.7612-151.0493-151.05S172.7114,104.9507,256,104.9507,407.05,172.7114,407.05,256,339.2886,407.05,256,407.05ZM413.98,124.1717a27.0945,27.0945,0,1,1,27.0945-27.0945A27.0946,27.0946,0,0,1,413.98,124.1717Z" transform="translate(0 0)" fill={color}/>
    </svg>
  )
}