// -----------------------------------------------------
// This file is generated by a script. DO NOT CHANGE IT!
// -----------------------------------------------------
import Nullstack from "nullstack";
export default ({width, height, length, title, rotation, animation, speed, class: klass, color = "currentColor"}) => {
  const transform = rotation ? `rotate(${rotation})` : false;
  const duration = {slow: "1.5s", fast: "0.5s"}[speed] || "1.0s";
  return (
    <svg width={width} height={height} transform={transform} class={klass} viewBox="0 0 512 512">
      {title && <title>{title}</title>}
      {animation === "spin" && <animateTransform attributeType="xml" attributeName="transform" type="rotate" from="360 0 0" to="0 0 0" dur={duration} additive="sum" repeatCount="indefinite" />}
      <path d="M484.6172,110.4043H27.3828A27.4136,27.4136,0,0,1,0,83.0215V27.3828A27.4136,27.4136,0,0,1,27.3828,0H484.6172A27.4139,27.4139,0,0,1,512,27.3828V83.0215A27.4139,27.4139,0,0,1,484.6172,110.4043Z" transform="translate(0 0)" fill={color}/>
      <path d="M484.6172,512H27.3828A27.4139,27.4139,0,0,1,0,484.6172V428.9785a27.4139,27.4139,0,0,1,27.3828-27.3828H484.6172A27.4142,27.4142,0,0,1,512,428.9785v55.6387A27.4142,27.4142,0,0,1,484.6172,512Z" transform="translate(0 0)" fill={color}/>
      <path d="M484.6172,311.2021H27.3828A27.4138,27.4138,0,0,1,0,283.8193V228.1807a27.4135,27.4135,0,0,1,27.3828-27.3828H484.6172A27.4138,27.4138,0,0,1,512,228.1807v55.6386A27.4142,27.4142,0,0,1,484.6172,311.2021Z" transform="translate(0 0)" fill={color}/>
    </svg>
  )
}