// -----------------------------------------------------
// This file is generated by a script. DO NOT CHANGE IT!
// -----------------------------------------------------
import Nullstack from "nullstack";
export default ({width, height, length, title, rotation, animation, speed, class: klass, color = "currentColor"}) => {
  const transform = rotation ? `rotate(${rotation})` : false;
  const duration = {slow: "1.5s", fast: "0.5s"}[speed] || "1.0s";
  return (
    <svg width={width} height={height} transform={transform} class={klass} viewBox="0 0 512 512">
      {title && <title>{title}</title>}
      {animation === "spin" && <animateTransform attributeType="xml" attributeName="transform" type="rotate" from="360 0 0" to="0 0 0" dur={duration} additive="sum" repeatCount="indefinite" />}
      <path d="M512,164.0312V111.504a17.9575,17.9575,0,0,0-17.9576-17.9575H17.9576A17.9575,17.9575,0,0,0,0,111.504v52.5272Z" transform="translate(0 0)" fill={color}/>
      <path d="M0,240.6873V400.4959a17.9576,17.9576,0,0,0,17.9576,17.9576H494.0424A17.9576,17.9576,0,0,0,512,400.4959V240.6873ZM113.685,373.3507H37.5856V337.4355H113.685Zm126.77,0h-99.3V337.4355h99.3Z" transform="translate(0 0)" fill={color}/>
    </svg>
  )
}